source 'https://rubygems.org'
ruby '2.1.2'

gem 'mandrill-api'
gem 'sinatra'
gem 'activerecord'
gem 'sinatra-activerecord'

group :development do
	gem 'sqlite3'
end

group :production do
	gem 'pg'
end